version: '3.8'

services:
  web:
    restart: always
    build: .
    ports:
      - '3000:3000'
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - type: bind
        source: ./webapp
        target: /webapp
    depends_on:
      - db
      - redis
    tty: true

  db:
    restart: always
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - type: bind
        source: ./db_data
        target: /var/lib/mysql
    tty: true

  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis:/data
