# RuboCop configuration file
# 参考: https://rubocop.readthedocs.io/en/stable/configuration/

plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'config/application.rb'
    - 'config/boot.rb'
    - 'config/environment.rb'
    - 'config/puma.rb'
    - 'config/spring.rb'
    - 'config/environments/*'
    - 'config/initializers/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'log/**/*'
    - 'storage/**/*'
    - 'node_modules/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'Gemfile.lock'
    - 'Rakefile'

# Style and formatting
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: no_comma

# Metrics
Metrics/BlockLength:
  Exclude:
    - 'config/routes.rb'
    - 'spec/**/*'
    - 'db/**/*'

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 150

Metrics/ModuleLength:
  Max: 150

# Layout
Layout/LineLength:
  Max: 120
  AllowedPatterns: ['(\A|\s)#']

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# Rails specific
Rails:
  Enabled: true

Rails/FilePath:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

# RSpec specific
RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 5

RSpec/DescribeClass:
  Exclude:
    - 'spec/requests/**/*'
    - 'spec/system/**/*'

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NestedGroups:
  Max: 5
